lilit/lilitsite/urls.py
from django.contrib import admin
from django.urls import path,include
from main.views import PostAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('api/postlist/', PostAPIView.as_view())
]

lilit/main/urls.py
from django.urls import path

from . import views
from .views import HomePageListView, CreatePost, ShowPost, ReplyView, ShowCats, ProfileView

urlpatterns = [
    path("", HomePageListView.as_view(), name="main"),
    path('create/',CreatePost.as_view(),name='create_post'),
    path('posts/<slug:slug>/', ShowPost.as_view(), name='posts'),
    path('reply/<int:com_id>/', ReplyView.as_view(), name='reply'),
    path('category/<slug:slug>/', ShowCats, name='categories'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile')
]

lilit/users/urls.py
from django.urls import path

from . import views
from .views import LoginUser, RegisterUser

app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registrate/', RegisterUser.as_view(), name='registrate'),
]

lilit/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse


class Post(models.Model):
    name=models.CharField(max_length=64)
    content=models.TextField(null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    category=models.ForeignKey('Category', related_name='categories', on_delete=models.PROTECT, null= True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=2, )
    slug=models.SlugField(max_length=200, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            slug = base_slug
            counter = 1
            while Post.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('posts', kwargs={'slug': self.slug})
class Category(models.Model):
    category_name=models.CharField(max_length=32)
    slug=models.SlugField(max_length=32, blank=True)

    def save(self, *args,**kwargs):
        if not self.slug:
            slug=slugify(self.category_name)
            self.slug=slug
        super().save(*args, **kwargs)
    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('categories',kwargs={'slug':self.slug})


class Comment(models.Model):
    comment_content=models.TextField(max_length=500)
    comment_author = models.ForeignKey(User,related_name='author', on_delete=models.CASCADE, default=2)
    comment_post = models.ForeignKey("Post", related_name="com_of_post", on_delete=models.CASCADE, null=True)
    reply=models.ForeignKey('self', related_name='replies',on_delete=models.CASCADE, null=True,blank=True)
    time_created=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.comment_content

lilit/users/models.py
from django.db import models

# Create your models here.

lilit/main/forms.py
from django import forms

from .models import Comment


class AddCommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['comment_content']

lilit/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    class Meta:
        model=get_user_model()
        fields=['username','password']

class RegisterUserForm(UserCreationForm):

    class Meta:
        model=get_user_model()
        fields=['username','email', 'password1', 'password2']

    def cleaned_email(self):
        email=self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("E-mail already exists")
        return email

lilit/main/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, DetailView
from rest_framework.generics import ListAPIView

from .forms import AddCommentForm
from .models import (Post, Comment, Category)
from .serializers import PostSerializer


class HomePageListView(ListView):
     model=Post
     template_name = 'main/home_page.html'
     context_object_name = 'posts'
     extra_context = {
          'title': 'Main Page',
     }

def ShowCats(request, slug):
     a=get_object_or_404(Category, slug=slug)
     b=Post.objects.filter(category=a)
     data={'title':a,
           'cat': b
           }
     return render(request,'main/category.html', data)

class CreatePost(CreateView):
     model = Post
     template_name = 'main/create_post.html'
     fields = ['name','content','category']


     extra_context = {'title':'Create post'}

     def form_valid(self, form):
          form.instance.author=self.request.user
          return super().form_valid(form)


class ProfileView(DetailView):
     model = User
     template_name = 'main/profile.html'


class ShowPost(View):
     def get(self, request, slug):
          post = get_object_or_404(Post, slug=slug)
          form = AddCommentForm()
          comms = post.com_of_post.all()

          return render(request, 'main/post.html', {'post': post, 'form': form, 'com':comms})

     def post(self, request, slug):
          post = get_object_or_404(Post, slug=slug)
          form = AddCommentForm(request.POST)

          if form.is_valid():
               comment = form.save(commit=False)
               form.instance.comment_author = self.request.user
               comment.comment_post = post
               comment.save()
               return redirect('posts',slug)  # Перенаправление на детальную страницу поста
          return render(request, 'main/post.html', {'post': post, 'form': form})

class ReplyView(CreateView):
     model = Comment
     template_name = "main/reply.html"

     def get_success_url(self):
          next_url = self.request.GET.get('next')
          if next_url:
               return next_url
          return reverse_lazy('main')
     fields = ['comment_content']

     def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)
          context['com_id']=self.kwargs['com_id']
          context['com_name']=get_object_or_404(Comment, pk=self.kwargs['com_id'])
          return context

     def form_valid(self, form):
          reply_com = get_object_or_404(Comment, pk=self.kwargs['com_id'])
          form.instance.comment_author=self.request.user
          form.instance.reply=reply_com
          return super().form_valid(form)



class PostAPIView(ListAPIView):
     queryset = Post.objects.all()
     serializer_class = PostSerializer

lilit/users/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
from .forms import LoginUserForm, RegisterUserForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': "Authorisation"}
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('main')
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/registrate.html'
    extra_context = {'title':'Registration'}
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('main')

    def form_valid(self, form):
        #сохранение формы и создание объекта пользователя ( self.object).
        response = super().form_valid(form)
        #Функция login()принимает текущий запрос и недавно созданный объект пользователя ( self.object)
        login(self.request, self.object)
        # Перенаправление на et_success_url
        return response

def logout_user(request):
    logout(request)
    return(redirect('main'))

# Create your views here.

lilit/main/templates/main/1.html
<p>{{i.comment_author}}----created at {{i.time_created}}</p>
<h2>{{ i.comment_content}}</h2>
{% if user.is_authenticated %}
<h4><a href="{% url 'reply' i.pk %}?next={{request.path}}">reply</a></h4>
{% endif %}
<h4>replies</h4>
<ul>
    {% for l in i.replies.all %}
        <li>author:{{l.comment_author}}-----{{ l.comment_content }}</li>
    {% endfor %}
</ul>

lilit/main/templates/main/category.html
{% extends 'base.html' %}
{% block content %}
{% for i in cat %}
-----------------
    <p>author:{{i.author.username}}</p>
    <p><h2>{{i}}</h2></p>
    <p><h3>{{i.text}}</h3></p>
    <p><a href="{{i.get_absolute_url}}">More</a></p>
{% endfor %}
{% endblock %}

lilit/main/templates/main/comment.html
<p>{{i.comment_author}}----created at {{i.time_created}}</p>
<h3>{{ i.comment_content}}</h3>
{% if user.is_authenticated %}
<h4><a href="{% url 'reply' i.pk %}?next={{request.path}}">reply</a></h4>
{% endif %}
<ul>
{% for i in i.replies.all %}
{% include 'main/comment.html' with i=i%}
{% endfor %}
</ul>

lilit/main/templates/main/create_post.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

lilit/main/templates/main/home_page.html
{% extends 'base.html' %}
{% block content %}
{% for i in posts %}
    <a href="{{i.get_absolute_url}}" class="post-link">
    <div id="post" >
        <p>{{i.author.username}}</p>
        <p><h3>{{i}}</h3></p>
        <p>{{i.content|truncatechars:400}}</p>

    </div>
    </a>
    <hr>
{% endfor %}
{% endblock %}

lilit/main/templates/main/post.html
{% extends 'base.html' %}
{% block content %}
<h1>{{post.name}}</h1>
<p>{{post.content}}</p>
<p>author-{{post.author}}----created at{{post.created_at}}</p>
{% if user.is_authenticated %}
<form method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% else %}
<p >To make comments login</p>
{% endif %}
{% for i in com %}
{% include 'main/comment.html' with i=i%}
{% empty %}
    <p>No comments</p>
{% endfor %}
{% endblock %}

lilit/main/templates/main/profile.html
{% extends 'base.html' %}
{% block content %}
<p>Username:{{object.username}}</p>
<p>Firstname: {{object.firstname}}</p>
<p>Lastname:{{object.lastname}}</p>
{% endblock %}

lilit/main/templates/main/reply.html
{% extends 'base.html' %}
{% block content %}
<p>{{com_name}}</p>

<form method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

lilit/templates/base.html
{% load main_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://fonts.cdnfonts.com/css/reddit-sans?version=1.0" rel="stylesheet" type="text/css"/>
    <link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<div class="header">
    <div id="go-main">
    {% get_menu as menu %}
    {% for i in menu %}
        <a href="{% url i.url %}" id="logo"><img src="{% static 'main/images/logo.png' %}" alt="Описание изображения" style="border: none;" id="logo-img"></a>
    {% endfor %}
    </div>
    <div id="user">
        {% if user.is_authenticated %}
            <a href="{%url 'create_post'%} ">Create post</a>
            <a href="{% url 'users:logout' %}">Logout</a>
            <a href="{% url 'profile' request.user.pk %}">Profile</a>
        {% else %}
            <a href="{% url 'users:login'%}?next={{request.path}}">Login</a>/<a href="{% url 'users:registrate'%}?next={{request.path}}">Sing in</a>
        {% endif %}
    </div>
</div>
<aside class="sidebar">
    <div class="sidebar-section">
    {% get_categories as cats %}
        <button class="dropdown-btn">Categories</button>
        <div class="dropdown-menu">
            {% for el in cats %}
            <a href="{{ el.get_absolute_url }}" class="cats">{{el.category_name}}</a>
            {% endfor %}
        </div>
    </div>
<div class="content" >
<h1>{{title}}</h1>

{% block content %}

{% endblock %}
</div>
</aside>
</body>
</html>

lilit/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Login</button></p>
</form>

</body>
</html>

lilit/users/templates/users/registrate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Sing Up</button> </p>
</form>
</body>
</html>